const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.resolve(__dirname,'..');
let legacy=false,calls=[],doc={email:'demo@test.fr',wordsValidated:12,validatedWords:{niveau1:['Hello']},wordHistory:[]};
const collection={findOne:async q=>q.emailHash&&!legacy||q.email?doc:null,updateOne:async(q,u)=>{calls.push({q,u});return{matchedCount:q.emailHash&&legacy?0:1};}};
const sandbox={module:{exports:{}},Date,console,require:name=>{
 if(name==='nanoid')return{nanoid:()=> 'id'};
 if(name==='bcryptjs')return{};
 if(name==='./db')return{getDB:()=>({collection:()=>collection})};
 if(name==='./crypto')return{encryptField:x=>x,decryptField:x=>x,hashForLookup:x=>'hash:'+x};
 if(name==='./wordService')return{LEVELS:['niveau1','niveau2','niveau3']};
 throw new Error(name);
}};
vm.runInNewContext(fs.readFileSync(path.join(root,'services/userService.js'),'utf8'),sandbox);
const service=sandbox.module.exports,entry={language:'en',level:'niveau1',word:'Hello',translation:'Bonjour'},now=new Date('2026-01-01T12:00:00Z');
(async()=>{
 await service.recordWordSeen(' DEMO@TEST.FR ',entry,now);
 assert.equal(calls.length,1);assert.equal(calls[0].q.emailHash,'hash:demo@test.fr');
 assert.equal(calls[0].u.$push.wordHistory.$slice,-1000);
 assert.equal(calls[0].u.$push.wordHistory.$each[0].seenAt,now.toISOString());
 assert.equal(doc.wordsValidated,12);assert.deepEqual(doc.validatedWords,{niveau1:['Hello']});
 doc.wordHistory=[{...entry,seenAt:now.toISOString()}];calls=[];
 await service.recordWordSeen('demo@test.fr',entry,now);assert.equal(calls.length,0);
 await service.recordWordSeen('demo@test.fr',{...entry,language:'es'},now);assert.equal(calls.length,1);
 legacy=true;calls=[];doc.wordHistory=[];
 await service.recordWordSeen('demo@test.fr',entry,now);assert.equal(calls.length,2);assert.equal(calls[1].q.email,'demo@test.fr');
 assert.equal(service.toSafeUser({...doc,passwordHash:'secret',emailHash:'secret',emailEncrypted:'secret'}).wordHistory,undefined);
 legacy=false;calls=[];const lesson={language:'en',level:'niveau1',lessonId:'quotidien-heures'};
 await service.recordLessonSeen('demo@test.fr',lesson,now);
 assert.equal(calls.length,1);assert.equal(calls[0].u.$push.lessonHistory.$slice,-1000);
 assert.equal(calls[0].u.$push.lessonHistory.$each[0].seenAt,now.toISOString());
 doc.lessonHistory=[{...lesson,seenAt:now.toISOString()}];calls=[];
 await service.recordLessonSeen('demo@test.fr',lesson,now);assert.equal(calls.length,0);
 await service.recordLessonSeen('demo@test.fr',{...lesson,level:'niveau2'},now);assert.equal(calls.length,1);
 calls=[];legacy=true;doc.lessonHistory=[];
 await service.recordLessonSeen('demo@test.fr',lesson,now);assert.equal(calls.length,2);assert.equal(calls[1].q.email,'demo@test.fr');
 assert.equal(service.toSafeUser(doc).lessonHistory,undefined);
 assert.equal(doc.wordsValidated,12);assert.deepEqual(doc.validatedWords,{niveau1:['Hello']});
 console.log('PASS : historiques mots/fiches datés, dédoublonnage journalier, langue/niveau séparés, anciens comptes, progression conservée, historiques internes masqués (base simulée).');
})().catch(e=>{console.error(e);process.exitCode=1;});
